import = [
  "~/.config/alacritty/themes/themes/one_dark.toml"
]

[font]
size = 15.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style  = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style  = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style  = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style  = "Regular"

[env]
TERM = "xterm-256color"
