* Dotfiles

This is more a note for future me, but feel free to use anything you like.

** Requirements

My current default development setup includes:

- ~fish~ shell
- ~homebrew~ for mac
- ~git~ comes installed with most *nix operating systems.
- ~asdf~ for versions of various runtimes (languages like ruby, node, sbcl etc.)

** Installation

Clone the repo and symlink the files and directories to respective locations in home. For example:

#+begin_src bash
  git clone git@github.com:akagr/dotfiles.git ~/dotfiles

  ln -s ~/dotfiles/dot-emacs-dot-d ~/.emacs.d
  ln -s ~/dotfiles/dot-gitconfig ~/.gitconfig
#+end_src

*** Git setup

Linking ~.gitconfig~ brings most of my customisations, but we need to install ~gnupg~ and ~pinentry-mac~ to sign commits. Once both of these are install, inform ~git~
 of ~pinentry-mac~ with:

 #+begin_src bash
   echo "pinentry-program $(which pinentry-mac)" >> ~/.gnupg/gpg-agent.conf
   gpgconf --kill gpg-agent
 #+end_src

Additionally, import an existing GPG key with:

#+begin_src bash
  gpg --import private.key
#+end_src

Or, to generate a new key and add it to Github, follow [[https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key][github documentation for generating keys]].
