* Dotfiles

This is more a note for future me, but feel free to use anything you like.

** Requirements

Following is a list of a few things I always install before linking any of the dotfiles. Everything mentioned here is installable via ~homebrew~, once that's set up.

- [[https://brew.sh/][homebrew]] for mac and linux
- [[https://fishshell.com/][fish]] shell
- [[https://asdf-vm.com/][asdf]] for versions of various runtimes (languages like ruby, node, sbcl etc.)
- [[https://github.com/tmux/tmux/wiki][tmux]] mainly for tabbing multiple shell sessions, but detach/attach does come in handy sometimes
- [[https://www.gnu.org/software/emacs/][emacs]] is my main editor. I use [[https://github.com/d12frosted/homebrew-emacs-plus][emacs-plus]] flavor because I find it works best for my on a mac.
- [[https://github.com/Homebrew/homebrew-cask-fonts][homebrew fonts]] is a repository for all the nerd fonts

*** Optional

The optional packages aren't mandatory for me to get a productive environment. I've worked on these, but don't always set them up on all my machines.

- [[https://neovim.io/][neovim]] is a secondary editor I sometimes use, and have riced up a bit.

** Installation

Clone the repo and symlink the files and directories to respective locations in home. For example:

#+begin_src bash
  git clone git@github.com:akagr/dotfiles.git ~/dotfiles

  ln -s ~/dotfiles/dot-emacs-dot-d ~/.emacs.d
  ln -s ~/dotfiles/dot-gitconfig ~/.gitconfig
  ln -s ~/dotfiles/dot-tmux-dot-conf ~/.tmux.conf
  ln -s ~/dotfiles/nvim ~/.config/nvim
  mkdir -p ~/.config/fish
  ln -s ~/dotfiles/config.fish ~/.config/fish/config.fish
#+end_src

*** Emacs setup
After linking the dotfiles and starting emacs, all the package installation happens automatically. Once it settles, we need to run two lisp expressions.
=Note=: These can also be run interactively using ~M-x~.

#+BEGIN_SRC emacs-lisp
  (all-the-icons-install-fonts)
  (nerd-icons-install-fonts)
#+END_SRC
*** Git setup

Linking ~.gitconfig~ brings most of my customisations, but we need to install ~gnupg~ and ~pinentry-mac~ to sign commits. Once both of these are install, inform ~git~
 of ~pinentry-mac~ with:

 #+begin_src bash
   echo "pinentry-program $(which pinentry-mac)" >> ~/.gnupg/gpg-agent.conf
   gpgconf --kill gpg-agent
 #+end_src

Additionally, import an existing GPG key with:

#+begin_src bash
  gpg --import private.key
#+end_src

Or, to generate a new key and add it to Github, follow [[https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key][github documentation for generating keys]].

** Why name the files ~dot-tmux-dot-conf~ instead of ~.tmux.conf~

Any file starting with a period (.) is hidden on most *nix systems. All the subject files which I use this repo to backup and share are named so, so that they are always visible. While linking, I use correct names for the symlinks.
